import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { AppFeaturesProvider } from "./_context/AppContext";
import { DarkModeProvider } from "./_context/DarkModeContext";
import BackgroundImage from "./_components/BackgroundImage";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppFeaturesProvider>
        <DarkModeProvider>
          <body className="max-w-screen-2xl mx-auto bg-white dark:bg-[#313E51] relative">
            <div className=" min-h-screen relative w-full">
              <BackgroundImage />
              <Header />
              {children}
            </div>

            <Toaster
              position="top-center"
              gutter={12}
              containerStyle={{ margin: "8px" }}
              toastOptions={{
                success: {
                  duration: 3000,
                },
                error: {
                  duration: 5000,
                },
                style: {
                  fontSize: "16px",
                  maxWidth: "500px",
                  padding: "16px 24px",
                },
              }}
            />
          </body>
        </DarkModeProvider>
      </AppFeaturesProvider>
    </html>
  );
}
