import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Header from "./_components/Header";
import { AppFeaturesProvider } from "./_context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppFeaturesProvider>
        <body className={`max-w-screen-2xl mx-auto`}>
          <Header />
          <div className="xl:grid-rows-1 xl:grid-cols-[auto_1fr] grid grid-rows-[1fr_auto] min-h-screen">
            <Sidebar />
            {children}
          </div>

          <Toaster
            position="top-center"
            gutter={12}
            containerStyle={{ margin: "8px" }}
            toastOptions={{
              success: {
                duration: 3000,
              },
              error: {
                duration: 5000,
              },
              style: {
                fontSize: "16px",
                maxWidth: "500px",
                padding: "16px 24px",
              },
            }}
          />
        </body>
      </AppFeaturesProvider>
    </html>
  );
}
